### ISSUE TITLE
New Feaures From Dev-Branch - [opened]

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-oebl-research-tool-front-end#135]
In GitLab by @PhilipRoeggla on Jun 22, 2022, 10:22

_Merges dev-backup -> master_

After resolving https://gitlab.com/acdh-oeaw/oebl/oebl-irs-devops/-/issues/49, we can now add changes from dev.

- Refactored lemma importer
- Print lemma

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Jun 22, 2022, 10:22

approved this merge request

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Jun 22, 2022, 10:23

enabled an automatic merge when the pipeline for 2271be7dfb4f957380fe92dbddfc3675f9b30943 succeeds

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Jun 22, 2022, 13:41

aborted the automatic merge because source branch was updated

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Jun 22, 2022, 13:41

added 4 commits

<ul><li>bce3125d - Consuming The New Notes Field Manualy</li><li>cd29c669 - Adding Label for Notes</li><li>d2f61c5a - UX for Notes Field</li><li>3be31f0b - Merge branch &#39;60-kommentarfeld&#39; into &#39;dev-backup&#39;</li></ul>

[Compare with previous version](/acdh-oeaw/oebl/oebl-research-tool-front-end/-/merge_requests/47/diffs?diff_id=422286436&start_sha=2271be7dfb4f957380fe92dbddfc3675f9b30943)

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Aug 2, 2022, 10:48

added 4 commits

<ul><li>3be31f0b...9a4a0a2c - 3 commits from branch <code>master</code></li><li>3ce5db80 - Merge branch &#39;76-super-cool-editor&#39; into &#39;dev-backup&#39;</li></ul>

[Compare with previous version](/acdh-oeaw/oebl/oebl-research-tool-front-end/-/merge_requests/47/diffs?diff_id=451693086&start_sha=3be31f0bf02933495bd447e119105167ae73557a)

**Comment by stefanprobst** [comment]
i dont think there is anything actionable here anymore, closing.
